### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module

### ISSUE THREAD

**Issue by anark** [jorgebucaran/colorette#55] opened 2020-12-01 21:55 UTC
I am running into a strange issue that started when updating tailwind/postcss packages that use colorette and running webpack via react-cypress-unit-test testing library.

The error I am getting is

```
Webpack Compilation Error
./app/javascript/components/Input/Input.tsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: ./node_modules/colorette/index.js
require() of ES modules is not supported.
require() of ./node_modules/colorette/index.js from ./node_modules/postcss/lib/css-syntax-error.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from ./node_modules/colorette/package.json.
```

If I explicitly install colorette 1.2.0 instead of 1.2.1 everything seems to work fine.

**Comment by jorgebucaran** [comment] 2020-12-02 04:25
Hey! Are you using Node 13.5? Please make sure this is not a dupe of #53.

**Comment by anark** [comment] 2020-12-02 07:04
I'm using Node 15, however I only see this error when running it through react-cypress-unit-test.  I checked that it is still running from Node 15 there and it is, however it may have something to do with how that library is initializing webpacker as I don't get this issue when I run it normally, just when running through cypress.

**Comment by jorgebucaran** [comment] 2020-12-02 07:10
Thanks for the info @anark. It must have something to do with how react-cypress-unit-test uses Colorette (or one of its dependencies) and not with Colorette itself. Do please let us know if you find out anything.

**Closed by jorgebucaran** 2020-12-02 07:10 UTC
