### ISSUE TITLE
Plain `require("colorette")` doesn't work anymore

### ISSUE THREAD

**Issue by anko** [jorgebucaran/colorette#50] opened 2020-07-18 12:54 UTC
repro:

```
$ cd $(mktemp --directory)
$ npm i colorette
[ normal npm install output, installing colorette@1.2.1 ]
$ node
Welcome to Node.js v13.2.0.
Type ".help" for more information.
> require('colorette')
Thrown:
Error: No valid exports main found for '/tmp/tmp.rXILKO7iaG/node_modules/colorette'
    at resolveExportsTarget (internal/modules/cjs/loader.js:611:9)
    at applyExports (internal/modules/cjs/loader.js:492:14)
    at resolveExports (internal/modules/cjs/loader.js:541:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:643:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:941:27)
    at Function.Module._load (internal/modules/cjs/loader.js:847:27)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (internal/modules/cjs/helpers.js:69:18) {
  code: 'MODULE_NOT_FOUND'
}
>
```

This broke in [v1.2.1](https://github.com/jorgebucaran/colorette/releases/tag/1.2.1), so ref #44 #45  (Doing the same but `npm i colorette@<1.2.1` works as expected.)

If this is intentional, it breaks the semantic versioning promise; API break means you should increment the major version number, i.e. `2.x.x`.

**Comment by jorgebucaran** [comment] 2020-07-18 14:33
Duplicate of https://github.com/jorgebucaran/colorette/issues/48 and https://github.com/jorgebucaran/colorette/issues/46.


@anko Some versions in the Node 13.x range have buggy ES module support or need --experimental-modules in the command line, so please upgrade to Node >=13.7 or downgrade to 12. 👋

**Closed by jorgebucaran** 2020-07-18 14:33 UTC
