### ISSUE TITLE
No valid exports main found for node_modules/colorette

### ISSUE THREAD

**Issue by tcampbPPU** [jorgebucaran/colorette#53] opened 2020-08-25 02:15 UTC
**Describe the bug**
With Nuxt.js running on macOS with version 13.5 of Node.js `$ nuxt` && `$ nuxt build` fail with error
```
No valid exports main found for '/Users/node_modules/colorette'
```
**To Reproduce**
1. Be running Mac OS
2. with NVM install and use node version 13.5.0
3. run `$ nuxt` or `$ nuxt build` within a Nuxt.js project
4. See error for No valid exports

**Expected behavior**
Nuxtjs to build and compile successfully

**My Enviornment**
MacOS Catalina Version - **10.15.2**
Node version - **13.5.0**
Nuxt.js version -  **2.13.3**

**Comment by tcampbPPU** [comment] 2020-08-25 02:21
To Note, I also have a Ubuntu laptop (20.04) running the same version of Node.js and Nuxt.js and I do not see any error when compiling my project.

**Comment by jorgebucaran** [comment] 2020-08-25 03:38
@tcampbPPU This is a duplicate of https://github.com/jorgebucaran/colorette/issues/48 or https://github.com/jorgebucaran/colorette/issues/46. You just need to upgrade Node to 14 or downgrade to 12.

**Closed by jorgebucaran** 2020-08-25 03:38 UTC

**Comment by tcampbPPU** [comment] 2020-08-25 03:53
Ok, I will try downgrading to version 12, actully node 14 gives me sperate issue with Nuxt 🤦🏼 .

**Comment by Risto-Stevcev** [comment] 2020-09-10 13:14
@jorgebucaran Is it possible to revert this back to non-es6 syntax and do a minor version bump to 1.1.2, and then re-introduce it back but do a major version bump to 2.0.0?
that way it won't break existing code unless to do a major version bump
